[package]
name = "rpgffi"
version = "0.0.1"
authors = ["posi@planet.com", "Jason Dusek <jason.dusek@gmail.com>"]
build = "build.rs"
description = "Bindgen generated bindings for postgresql 9.4 and 9.5"
keywords = ["postgresql"]
license = "Apache-2.0/PostgreSQL"
repository = "http://github.com/posix4e/rpgffi"
